name: Test

on: [push, pull_request]

jobs:
  openjdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - run: sbt compile
